#!/bin/bash
# Fix ngrok domain issue

echo "🔧 Fixing ngrok domain issue for AI-STER..."
echo ""
echo "Your ngrok account requires a registered domain."
echo ""
echo "You have two options:"
echo ""
echo "1. Register 'aister.ngrok.app' domain:"
echo "   - Go to https://dashboard.ngrok.com/domains"
echo "   - Register the domain 'aister.ngrok.app'"
echo "   - Then run: ngrok http 8501 --domain=aister.ngrok.app"
echo ""
echo "2. Use a free ngrok account (with random URL):"
echo "   - Create a new free ngrok account at https://ngrok.com/signup"
echo "   - Get the authtoken from https://dashboard.ngrok.com/get-started/your-authtoken"
echo "   - Run: ngrok config add-authtoken YOUR_NEW_TOKEN"
echo "   - Then run: ngrok http 8501"
echo ""
echo "3. Use alternative tunneling service (Cloudflare Tunnel):"
echo "   - Install: curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o bin/cloudflared"
echo "   - Make executable: chmod +x bin/cloudflared"
echo "   - Run tunnel: ./bin/cloudflared tunnel --url http://localhost:8501"
echo ""
echo "Current status:"
ps aux | grep -E "(streamlit|ngrok)" | grep -v grep
echo ""
echo "To access your app locally (without tunnel): http://localhost:8501"
